name: nma-dl
dependencies:
  - python=3.9
  - requests
  - numpy
  - scipy
  - matplotlib
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - ipywidgets
  - pathlib
  - tqdm
  - pandas
  - pillow
  - imageio
  - seaborn
  - nltk
  - tensorboard
  - flask
  - coloredlogs
  - conda-forge::fasttext
  - conda-forge::imageio-ffmpeg
  - pip
  - pip:
    - accelerate
    - altair
    - datasets
    - diffusers
    - evaluate
    - facenet-pytorch
    - flair
    - flasgger
    - flask-restful
    - libsixel-python
    - pyngrok
    - pytorch-pretrained-biggan
    - python-Levenshtein
    - textattack
    - tokenizers
    - transformers
    - vibecheck
